-------------------------------------------------------------------------------
-- lgn

local lgn = {}

function lgn.exe(name)
    local target = {}

    return target
end

function lgn.shared(name)
    local st = {}
    return st
end

function lgn.static(name)
    local st = {}
    return st
end

function lgn.toolchain(name)
    local tc = {}
    tc.name = name
    tc.tools = {}

    function tc.add_tool(tool)
        tc.tools[#tc.tools] = tool        
    end

    return tc
end

function lgn.ninja_writer(name)
    local nw = {}
    nw.name = name
    nw.lines = {}

    function nw:dump()
        return table.concat(self.lines, "\n")
    end

    function nw:add_comment(c)
        self.lines[#self.lines] = "# " .. c
    end

    return nw
end

-------------------------------------------------------------------------------
-- util 

local util = {}

function util.write_file(path, content)
    local f = io.open(path, "w")
    f:write(content)
    f:close()
end

local function main()
    local llab = lgn.exe("llab")
    local tc = lgn.toolchain("gcc")

    local bn = lgn.ninja_writer("build.ninja")
    bn:add_comment("This file is used to build llab.")
    bn.add_comment("It is generated by configure.lua.")

    util.write_file("./out" .. bn.name, bn:dump())
end

main()